export const GAME_SYMBOLS = {
  CROSS: 1,
  ZERO: 2,
  TRIANGLE: 3,
  SQUARE: 4,
};

export const MOVE_ORDER = [
  GAME_SYMBOLS.CROSS,
  GAME_SYMBOLS.ZERO,
  GAME_SYMBOLS.TRIANGLE,
  GAME_SYMBOLS.SQUARE,
];
